dut_config:
  dut_user: gfx
package_config:
  # if this key is not set, the main script will give a default name
  #package_name: '__name__'
  package_name: 'intelgputools'
latest_commits:
  value: True # (set to True/False)
  libinput: False
  glamor: False
  libva: False
  libva-utils: False
  intel-vaapi-driver: False
  cairo: True
  macros: False
  x11proto: False
  libxtrans: False
  libX11: False
  libXext: False
  dri2proto: False
  glproto: False
  libpciaccess: False
  pixman: False
  drm: True
  mesa: False
  xserver: False # (xserver) has the library 'glamour' modesetting
  libXfont: False
  xkeyboard-config : False
  xkbcomp : False
  xf86-input-mouse: False
  xf86-input-keyboard: False
  xf86-input-evdev: False
  xf86-input-joystick: False
  xf86-input-libinput: False # dependencies issue
  xf86-input-magictouch: False # compilation issue
  xf86-input-microtouch: False # compilation issue
  xf86-input-mutouch: False
  xf86-input-synaptics: False
  xf86-input-vmmouse: False
  xf86-video-vmware: False
  xf86-video-qxl: False
  xf86-video-amdgpu: False
  xf86-video-ati: False
  xf86-video-radeonhd: False
  xf86-video-modesetting: False
  xf86-video-chips: False
  xf86-video-vesa: False
  xf86-input-wacom: False
  # xf86-video-fbdev will not compile with the latest commit, please see (HowTo.d) folder (a Framebuffer device based X server)
  xf86-video-fbdev: False
  xproto: False
  xrdb: False
  # (xf86_video_intel) has the library 'sna'
  xf86-video-intel: False
  intel-gpu-tools: True
  rendercheck: False
  piglit: True
specific_commit:
  value: False # (set to True/False)
  libinput: '' # this commit has autogen.sh tag : (libinput 1.8.1)
  glamor : '' # needs to be compiled togheter with xorg
  libva: ''
  libva-utils: ''
  intel-vaapi-driver: ''
  cairo: ''
  macros: ''
  x11proto : ''
  libxtrans : ''
  libX11: ''
  libXext: ''
  dri2proto: ''
  glproto: ''
  libpciaccess: ''
  pixman: ''
  drm: ''
  mesa: ''
  xserver: '' # (xserver) has the library 'glamour'
  libXfont: ''
  xkeyboard-config : ''
  xkbcomp : ''
  xf86-input-mouse: ''
  xf86-input-keyboard : ''
  xf86-input-evdev: ''
  xf86-video-vesa: ''
  xf86-video-fbdev: '' # this is a special commit (3cf99231199bd5bd9e681e85d9da1f9eb736e3e7)
  xf86-input-joystick: '' # not needed
  xf86-input-libinput: ''
  xf86-input-magictouch: '' # not needed
  xf86-input-microtouch: '' # not needed
  xf86-input-mutouch: '' # not needed
  xf86-input-synaptics: ''
  xf86-input-vmmouse: '' # not needed
  xf86-video-vmware: ''
  xf86-video-qxl: ''
  xf86-video-amdgpu: ''
  xf86-video-ati: ''
  xf86-video-radeonhd: '' # unable to compile
  xf86-video-modesetting: '' # unable to compile (not needed since Xserver has modesetting on it)
  xf86-video-chips: ''
  xf86-input-wacom: ''
  xproto: ''
  xrdb: '' # X-resourcess
  # (xf86_video_intel) has the library 'sna' and modesetting
  xf86-video-intel: '' # only will be build with master branch commit (72bb27a3a68ecc616ce2dc8e9a1d20354504562)
  intel-gpu-tools: ''
  rendercheck: ''
  piglit: ''
2D_Driver:
  # the driver that will be enable by default (this apply for Ubuntu 16.10)
  sna: False # = xf86-video-intel
  # (glamour) is the default driver in Ubuntu 16.10
  glamour: True # = modesetting
patchwork:
  # (checkBeforeBuild) set to True in order to test the patch/mbox outside of the compilation a catch possible erros 'faster option'
  checkBeforeBuild: True
  libinput:
    apply: False
    path: ''
  drm:
    apply: False
    path: ''
  mesa:
    apply: False
    path: ''
  xf86-video-intel:
    apply: False
    path: ''
  xf86-video-vesa:
    apply: False
    path: ''
  xf86-video-fbdev:
    apply: False
    path: ''
  xf86-input-evdev:
    apply: False
    path: ''
  xf86-input-keyboard:
    apply: False
    path: ''
  xf86-input-wacom:
    apply: False
    path: ''
  xkeyboard-config:
    apply: False
    path: ''
  xkbcomp:
    apply: False
    path: ''
  xf86-input-joystick:
    apply: False
    path: ''
  xf86-input-libinput:
    apply: False
    path: ''
  xf86-input-magictouch:
    apply: False
    path: ''
  xf86-input-microtouch:
    apply: False
    path: ''
  xf86-input-mouse:
    apply: False
    path: ''
  xf86-input-mutouch:
    apply: False
    path: ''
  xf86-input-synaptics:
    apply: False
    path: ''
  xf86-input-vmmouse:
    apply: False
    path: ''
  xf86-video-vmware:
    apply: False
    path: ''
  xf86-video-qxl:
    apply: False
    path: ''
  xf86-video-amdgpu:
    apply: False
    path: ''
  xf86-video-ati:
    apply: False
    path: ''
  xf86-video-radeonhd:
    apply: False
    path: ''
  xf86-video-modesetting:
    apply: False
    path: ''
  xf86-video-chips:
    apply: False
    path: ''
  pixman:
    apply: False
    path: ''
  glamor:
    apply: False
    path: ''
  libva:
    apply: False
    path: ''
  libva-utils:
    apply: False
    path: ''
  intel-vaapi-driver:
    apply: False
    path: ''
  cairo:
    apply: False
    path: ''
  macros:
    apply: False
    path: ''
  x11proto:
    apply: False
    path: ''
  libxtrans:
    apply: False
    path: ''
  libX11:
    apply: False
    path: ''
  libXext:
    apply: False
    path: ''
  dri2proto:
    apply: False
    path: ''
  glproto:
    apply: False
    path: ''
  xrdb:
    apply: False
    path: ''
  libpciaccess:
    apply: False
    path: ''
  xproto:
    apply: False
    path: ''
  xserver:
    apply: False
    path: ''
  libXfont:
    apply: False
    path: ''
  intel-gpu-tools:
    apply: False
    path: '__patch_location__'
  rendercheck:
    apply: False
    path: ''
  piglit:
    apply: False
    path: ''
miscellaneous:
  maximum_permitted_time: 10000 # (hours)
  mailing_list:
    - humberto.i.perez.rodriguez@intel.com
    - humberto.i.perez.rodriguez@linux.intel.com
  upload_package: True
  server_for_upload_package: linuxgraphics.intel.com
  server_user: gfxserver
